FROM python:3.9.15-bullseye
#FROM python:3.12-rc-bullseye

RUN mkdir /src
RUN mkdir /src/ocr_project
RUN mkdir /src/media

COPY ./ocr_project /src/ocr_project

COPY ./media /src/media

COPY db.sqlite3 /src

RUN pip install --upgrade pip
RUN pip install importlib_metadata
RUN pip install torch>=1.9.0 torchvision>=0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install -r /src/ocr_project/requirements.txt
#
WORKDIR /src/ocr_project

CMD ["celery", "-A", "ocr_project", "worker", "-l", "DEBUG"]
# CMD ["gunicorn", "-c", "gunicorn.conf.py", "project.wsgi"]
