# Generated by Django 4.1.3 on 2022-11-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='text',
            field=models.TextField(default='', max_length=2000, null=True),
        ),
    ]
