# Generated by Django 4.1.3 on 2022-11-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_alter_imagedata_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='clean_text',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
    ]
